# Generated by Django 3.2.10 on 2021-12-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='published_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='subject',
        ),
    ]
